//Enumeration Package
package controller;

//Enumeration Start

public enum Commands {
	
	
	ADD_LANGUAGE,ADD_STATUS,DELETE_GRAPHIC,ADD_TRANSITION,INSERT_NAME,CHANGE_NAME,
	CHANGE_TRANSITION,ADD_INITIAL_STATUS,ADD_FINAL_STATUS,CHECK_CHAIN,RUN_INPUTS, CLEAR, VIEW_ROUTE;
	

}//Enumeration End
